appName: "api-golang-ddd"
server:
  port: "11000"
  origin: "http://localhost:4000"
  header: "*"

mongo:
  database: "api-golang-ddd"
  collections:
    user: "user"

sql:
  databaseName:   "user"

kafka:
  group: "api-golang-ddd"
  topics:
    createdUser: "created-user-event"
    updatedUser: "updated-user-event"
    deletedUser: "deleted-user-event"