// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	utils "api.ddd/pkgs/message_bus/utils"
)

// IProducer is an autogenerated mock type for the IProducer type
type IProducer struct {
	mock.Mock
}

type IProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *IProducer) EXPECT() *IProducer_Expecter {
	return &IProducer_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function with given fields: eventType
func (_m *IProducer) SendMessage(eventType *utils.Event) {
	_m.Called(eventType)
}

// IProducer_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type IProducer_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - eventType *utils.Event
func (_e *IProducer_Expecter) SendMessage(eventType interface{}) *IProducer_SendMessage_Call {
	return &IProducer_SendMessage_Call{Call: _e.mock.On("SendMessage", eventType)}
}

func (_c *IProducer_SendMessage_Call) Run(run func(eventType *utils.Event)) *IProducer_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*utils.Event))
	})
	return _c
}

func (_c *IProducer_SendMessage_Call) Return() *IProducer_SendMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *IProducer_SendMessage_Call) RunAndReturn(run func(*utils.Event)) *IProducer_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewIProducer creates a new instance of IProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProducer {
	mock := &IProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
