// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IController is an autogenerated mock type for the IController type
type IController struct {
	mock.Mock
}

type IController_Expecter struct {
	mock *mock.Mock
}

func (_m *IController) EXPECT() *IController_Expecter {
	return &IController_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx
func (_m *IController) CreateUser(ctx *gin.Context) {
	_m.Called(ctx)
}

// IController_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type IController_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *IController_Expecter) CreateUser(ctx interface{}) *IController_CreateUser_Call {
	return &IController_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx)}
}

func (_c *IController_CreateUser_Call) Run(run func(ctx *gin.Context)) *IController_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *IController_CreateUser_Call) Return() *IController_CreateUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *IController_CreateUser_Call) RunAndReturn(run func(*gin.Context)) *IController_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx
func (_m *IController) DeleteUser(ctx *gin.Context) {
	_m.Called(ctx)
}

// IController_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type IController_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *IController_Expecter) DeleteUser(ctx interface{}) *IController_DeleteUser_Call {
	return &IController_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx)}
}

func (_c *IController_DeleteUser_Call) Run(run func(ctx *gin.Context)) *IController_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *IController_DeleteUser_Call) Return() *IController_DeleteUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *IController_DeleteUser_Call) RunAndReturn(run func(*gin.Context)) *IController_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function with given fields: ctx
func (_m *IController) GetAllUsers(ctx *gin.Context) {
	_m.Called(ctx)
}

// IController_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type IController_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *IController_Expecter) GetAllUsers(ctx interface{}) *IController_GetAllUsers_Call {
	return &IController_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx)}
}

func (_c *IController_GetAllUsers_Call) Run(run func(ctx *gin.Context)) *IController_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *IController_GetAllUsers_Call) Return() *IController_GetAllUsers_Call {
	_c.Call.Return()
	return _c
}

func (_c *IController_GetAllUsers_Call) RunAndReturn(run func(*gin.Context)) *IController_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function with given fields: ctx
func (_m *IController) GetUserById(ctx *gin.Context) {
	_m.Called(ctx)
}

// IController_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type IController_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *IController_Expecter) GetUserById(ctx interface{}) *IController_GetUserById_Call {
	return &IController_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx)}
}

func (_c *IController_GetUserById_Call) Run(run func(ctx *gin.Context)) *IController_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *IController_GetUserById_Call) Return() *IController_GetUserById_Call {
	_c.Call.Return()
	return _c
}

func (_c *IController_GetUserById_Call) RunAndReturn(run func(*gin.Context)) *IController_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function with given fields: ctx
func (_m *IController) Health(ctx *gin.Context) {
	_m.Called(ctx)
}

// IController_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type IController_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *IController_Expecter) Health(ctx interface{}) *IController_Health_Call {
	return &IController_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *IController_Health_Call) Run(run func(ctx *gin.Context)) *IController_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *IController_Health_Call) Return() *IController_Health_Call {
	_c.Call.Return()
	return _c
}

func (_c *IController_Health_Call) RunAndReturn(run func(*gin.Context)) *IController_Health_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx
func (_m *IController) UpdateUser(ctx *gin.Context) {
	_m.Called(ctx)
}

// IController_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type IController_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *IController_Expecter) UpdateUser(ctx interface{}) *IController_UpdateUser_Call {
	return &IController_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx)}
}

func (_c *IController_UpdateUser_Call) Run(run func(ctx *gin.Context)) *IController_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *IController_UpdateUser_Call) Return() *IController_UpdateUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *IController_UpdateUser_Call) RunAndReturn(run func(*gin.Context)) *IController_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewIController creates a new instance of IController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIController(t interface {
	mock.TestingT
	Cleanup(func())
}) *IController {
	mock := &IController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
