name: CI Action

on:
  pull_request:
    types: ['edited', 'synchronize', 'reopened']
    branches: ['main', 'develop']

jobs:
  Build_Project:
    runs-on: ubuntu-22.04
    steps:
      - name: Cloning Project
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Golang Dependencies
        run: make install

      - name: Build App
        run: make build

  Run_Unite_Test:
    needs: Build_Project
    runs-on: ubuntu-22.04
    steps:
      - name: Cloning Project
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Golang Dependencies
        run: make install

      - name: Execute Test
        run: make test